/**
 * Build-scope configuration.
 *
 * Static generation only touches the countries listed here. To roll out a
 * new country, add its ISO code to TARGET_COUNTRIES and run `npm run build`
 * again — nothing else in the codebase changes. Building country-by-country
 * keeps build memory bounded instead of pulling millions of global rows
 * into one build.
 *
 * Pilot run: India (the source dataset has no Nepal postal codes).
 */
// Add more countries by moving codes INTO the array below. The data for these is
// already loaded in Supabase — keep DISABLED codes OUT of the brackets (the
// manifest generator regexes any quoted 2-letter code inside the brackets, so a
// commented-out code INSIDE the array gets wrongly picked up).
//
// ROLLOUT NOTE: this list is now the FULL dataset (PT + AE intentionally excluded;
// see notes). The whole site does NOT fit in one GitHub Actions 6h job, so DON'T
// push-build everything — the push auto-trigger has been removed from deploy.yml.
// Roll out in subsets via the workflow's ONLY_COUNTRIES input. RO is ordered LAST
// because of its known Windows export ENOENT bug; if its job fails on CI, every
// country before it is already live and you re-run RO alone.
export const TARGET_COUNTRIES = [
  'IN', 'US', 'GB', 'JP', 'RU', // Already live!
  'PK', 'DE', 'FR', 'IT', 'ES', 'NL', 'PL', 'AT', 'CH', 'BE',
  'SE', 'NO', 'DK', 'FI', 'CZ', 'HU',
  // European batch:
  'IE', 'BG', 'HR', 'SK', 'SI', 'LT', 'LV', 'EE', 'LU', 'IS', 'RS', 'UA', 'MD',
  // Major-markets batch:
  'TR', 'KR', 'AR', 'AU', 'BR', 'ZA', 'CA', 'NZ', 'ID', 'SG', 'MX', 'MY',
  // Long tail — the rest of the dataset (load via ONLY_COUNTRIES batches):
  'PE', 'DZ', 'CO', 'BY', 'CN', 'PH', 'UY', 'LK', 'BD', 'MA', 'EC', 'AZ', 'CY',
  'TH', 'KE', 'PA', 'GT', 'DO', 'AL', 'MW', 'CR', 'CL', 'HT', 'MK', 'PF', 'PR',
  'RE', 'FO', 'BM', 'GP', 'MQ', 'IM', 'GF', 'MT', 'NC', 'HN', 'AX', 'GL', 'MC',
  'SM', 'GU', 'YT', 'VI', 'GG', 'LI', 'SJ', 'AD', 'JE', 'FM', 'MP', 'WF', 'MH',
  'PM', 'AI', 'AS', 'CC', 'CX', 'FK', 'GI', 'GS', 'HK', 'HM', 'IO', 'MO', 'NF',
  'NR', 'NU', 'PN', 'PW', 'TC', 'VA', 'WS',
  // Off-dataset additions (not in GeoNames; sourced + geocoded separately):
  'NP', // Nepal — 917 codes from official 1991 list, coords via GeoNames NP places
  'RO' // LAST — known build bug; isolate if it fails.
];

/**
 * Supabase's REST API caps a single response (default 1,000 rows, hard max
 * 10,000 even with .limit()). generateStaticParams must therefore paginate
 * with .range() in pages of this size to download every row.
 */
export const FETCH_PAGE_SIZE = 1000;

/**
 * Countries generated by THIS Next build. Normally all of TARGET_COUNTRIES,
 * but scripts/build-all.mjs sets BUILD_COUNTRIES to a subset per chunk:
 * generating ~180K+ routes in one build overflows the V8 call stack inside
 * Next, so large rollouts run as several chunked builds whose /out folders
 * are merged. Site-wide UI (header, footer, search dropdown, robots.txt)
 * always uses the full TARGET_COUNTRIES list.
 */
export const BUILD_COUNTRIES: string[] = process.env.BUILD_COUNTRIES
  ? process.env.BUILD_COUNTRIES.split(',')
    .map((s) => s.trim().toUpperCase())
    .filter(Boolean)
  : TARGET_COUNTRIES;